
namespace Falak {

    enum TokenCategory {
        MULTILINECOMMENT,
        COMMENT,
        BREAK,
        DEC,
        DO,
        ELSE,
        ELSEIF,
        FALSE,
        IF,
        INC,
        RETURN,
        TRUE,
        VAR,
        WHILE,
        SEMICOLON,
        STARTPARENTHESIS,
        ENDPARENTHESIS,
        STARTCURLYBRACES,
        ENDCURLYBRACES,
        OR,
        CIRCUMFLEX,
        AND,
        EQUALS,
        DIFEQUAL,
        LESSTHAN,
        LESSTHANEQUAL,
        GREATERTHAN,
        GREATERTHANEQUAL,
        PLUS,
        MINUS,
        MULTIPLICATION,
        SLASH,
        PERCENT,
        EXCLAMATION,
        IDENTIFIER,
        INTLITERAL,
        INT,
        CHAR,
        NEWLINE,
        WHITESPACE,
        OTHER
        
    }
}
